using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RoslynGenerator;

/// <summary>
/// [AutoToString] 속성이 붙은 partial class에 ToString() override를 자동 생성하는
/// IIncrementalGenerator 구현체입니다.
///
/// 사용법:
///   [AutoToString]
///   public partial class MyClass { public string Name {get;set;} public int Age {get;set;} }
///
/// 생성 결과:
///   partial class MyClass { public override string ToString() => $"MyClass(Name={Name}, Age={Age})"; }
/// </summary>
[Generator]
public sealed class AutoToStringGenerator : IIncrementalGenerator
{
    private const string AttributeName      = "AutoToStringAttribute";
    private const string AttributeNamespace = "AutoGen";
    private const string FullAttributeName  = $"{AttributeNamespace}.{AttributeName}";

    // ─────────────────────────────────────────────────────────────────────
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1단계: [AutoToString] 속성 정의를 컴파일에 주입 (PostInitializationOutput)
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("AutoToStringAttribute.g.cs", """
                // <auto-generated/>
                namespace AutoGen
                {
                    [System.AttributeUsage(System.AttributeTargets.Class)]
                    public sealed class AutoToStringAttribute : System.Attribute { }
                }
                """);
        });

        // 2단계: 속성이 있는 클래스 선택 (syntax filter → semantic transform)
        var classInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax cls && cls.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetClassInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        // 3단계: 소스 파일 생성
        context.RegisterSourceOutput(classInfos, GenerateSource);
    }

    // ─────────────────────────────────────────────────────────────────────
    private static ClassInfo? GetClassInfo(GeneratorSyntaxContext ctx)
    {
        var cls    = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls) as INamedTypeSymbol;
        if (symbol is null) return null;

        bool hasAttr = symbol.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == FullAttributeName);
        if (!hasAttr) return null;

        string ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : symbol.ContainingNamespace.ToDisplayString();

        var props = symbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .Select(p => p.Name)
            .ToList();

        return new ClassInfo(ns, symbol.Name, props);
    }

    // ─────────────────────────────────────────────────────────────────────
    private static void GenerateSource(SourceProductionContext ctx, ClassInfo info)
    {
        string interpolated = string.Join(", ", info.Properties.Select(p => $"{p}={{{p}}}"));
        string toStringBody = $"\"{info.ClassName}({interpolated})\"";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    partial class {info.ClassName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        public override string ToString() => $\"{info.ClassName}({interpolated})\";");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(info.Namespace))
            sb.AppendLine("}");

        ctx.AddSource($"{info.ClassName}.AutoToString.g.cs", sb.ToString());
    }

    // ─────────────────────────────────────────────────────────────────────
    private sealed class ClassInfo
    {
        public string Namespace  { get; }
        public string ClassName  { get; }
        public List<string> Properties { get; }

        public ClassInfo(string ns, string className, List<string> properties)
        {
            Namespace  = ns;
            ClassName  = className;
            Properties = properties;
        }
    }
}
